<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
/**
 * CategoryModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findModelByCategory(Category $category)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->leftJoin('o.model', 'm')
            ->addSelect('m')
            ->where('o.category = :category')
            ->setParameter('category', $category);
        return $query_builder->getQuery()->getResult();
    }

    
}