<?php

namespace AppBundle\Repository;

/**
 * EventLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLogRepository extends \Doctrine\ORM\EntityRepository
{
}
