<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FollowUpUser;
use AppBundle\Entity\Order;
/**
 * FollowUpUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowUpUserRepository extends \Doctrine\ORM\EntityRepository
{



    public function findOrderEventLog(Order $order, $event)
    {
        $query_builder = $this->createQueryBuilder('follow')
            ->where ('follow.user = :user')
            ->andWhere('follow.typeRef = \'' .FollowUpUser::TYPE_ORDER .'\'')
            ->andWhere('follow.refId = :order')
            ->andWhere('follow.event =  :event')
            ->setParameter('user', $order->getCustomer())
            ->setParameter('order', $order)
            ->setParameter('event', $event)
            ->orderBy('follow.createdAt', 'DESC');
        return $query_builder->getQuery()->getResult();
    }

}
