<?php

namespace AppBundle\Repository;

/**
 * ModelStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCache()
    {
        return $this->createQueryBuilder('o')
            ->where('o.id = 4 or o.id = 1');
    }
}
