<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Order;
use AppBundle\Entity\Model;
use AppBundle\Entity\OrderModelUp;

/**
 * ModelBuyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelBuyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findModelFromOrder(Order $orderSearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.order = :orderSearch')
            ->setParameter('orderSearch', $orderSearch);
        return $query_builder->getQuery()->getResult();
    }
    public function findModelFromOrderUp(OrderModelUp $orderSearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.orderModelUp = :orderSearch')
            ->setParameter('orderSearch', $orderSearch);
        return $query_builder->getQuery()->getResult();
    }

    public function findModelBuyFromOrderAndModel(Order $orderSearch, Model $modelSearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.order = :orderSearch')
            ->andWhere('o.model = :modelSearch')
            ->setParameter('orderSearch', $orderSearch)
            ->setParameter('modelSearch', $modelSearch);
        return $query_builder->getQuery()->getResult();
    }
}
