<?php

namespace AppBundle\Repository;

/**
 * ModelLicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelLicenseRepository extends \Doctrine\ORM\EntityRepository
{
}
