<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Model;
use AppBundle\Entity\OrderModelBasket;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;

/**
 * OrderModelBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderModelBasketItemRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findModelInBasket(Model $model)
    {
        $query_builder = $this->createQueryBuilder('basketItem')
            ->where('basketItem.model = :model')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('model', $model);
        return $query_builder->getQuery()->getResult();
    }

    public function findAllModelsInBasketForUser(User $user)
    {
        $query_builder = $this->createQueryBuilder('basketItem')
            ->leftJoin(OrderModelBasket::class, 'basket', 'WITH', 'basketItem.orderModelBasket = basket')
            ->where('basket.customer = :user')
            ->setParameter('user', $user);
        return $query_builder->getQuery()->getResult();
    }

    public function findItemsInBasket(OrderModelBasket $orderBasket)
    {
        $query_builder = $this->createQueryBuilder('basketItem')
            ->where('basketItem.orderModelBasket = :orderBasket')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('orderBasket', $orderBasket);
        return $query_builder->getQuery()->getResult();
    }

}
