<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Model;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;
use AppBundle\Entity\OrderModelUp;

/**
 * OrderModelUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderModelUpRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOrderFromRef(string $ref)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.reference = :ref')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('ref', $ref);
        return $query_builder->getQuery()->getResult();
    }

}
