<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Model;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;
use AppBundle\Entity\OrderModelUp;

/**
 * OrderModelBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderModelBasketRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findBasketForUser(User $user)
    {
        $query_builder = $this->createQueryBuilder('basket')
            ->where('basket.customer = :user')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('user', $user);
        return $query_builder->getQuery()->getResult();
    }

    public function findBasketFromIdForUser(Int $id)
    {
        $query_builder = $this->createQueryBuilder('basket')
            ->leftJoin(ModelStatus::class, 'sta', 'WITH', 'o.status = sta')
            ->where('basket.id = :id')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('id', $id);
        return $query_builder->getQuery()->getResult();
    }
    
}
