<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Maker;
use AppBundle\Entity\Model;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\SuggestionModel;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;
use AppBundle\Entity\ModelBuy;
use AppBundle\Entity\OrderModelBasket;
use AppBundle\Entity\OrderModelBasketItem;
use AppBundle\Entity\Order;
use AppBundle\Entity\Signal;

/**
 * SignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSignalNotValid()
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.enabled = :enabled')
            ->andWhere('o.status != ' . Signal::STATUS_UNVALID . '') // exclude awaiting payments orders
            ->setParameter('enabled', false)
            ->orderBy('o.createdAt', 'DESC');
        return $query_builder->getQuery()->getResult();
    }
}
