<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Maker;
use AppBundle\Entity\Model;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\Suggestion;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;
use AppBundle\Entity\ModelBuy;
use AppBundle\Entity\OrderModelBasket;
use AppBundle\Entity\OrderModelBasketItem;
use AppBundle\Entity\Order;

/**
 * SuggestionModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSuggestionModelForCategory(Category $categorySearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.categoryUp = :categorySearch')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('categorySearch', $categorySearch);
        return $query_builder->getQuery()->getResult();
    }

    public function findSuggestionModelForCategoryAndModel(Category $categorySearch, Model $modelSearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->leftJoin(Suggestion::class, 'sug', 'WITH', 'o.suggestion = sug')
            ->where('o.categoryUp = :categorySearch')
            ->andWhere('sug.model = :modelSearch')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('categorySearch', $categorySearch)
            ->setParameter('modelSearch', $modelSearch);
        return $query_builder->getQuery()->getResult();
    }
}
