<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Maker;
use AppBundle\Entity\Model;
use AppBundle\Entity\CategoryModel;
use AppBundle\Entity\SuggestionModel;
use AppBundle\Entity\Category;
use AppBundle\Entity\ModelStatus;
use AppBundle\Entity\ModelBuy;
use AppBundle\Entity\OrderModelBasket;
use AppBundle\Entity\OrderModelBasketItem;
use AppBundle\Entity\Order;

/**
 * SuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSuggestionForModel(Model $modelSearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->where('o.model = :modelSearch')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('modelSearch', $modelSearch);
        return $query_builder->getQuery()->getResult();
    }

    public function findSuggestionForCategory(Category $categorySearch)
    {
        $query_builder = $this->createQueryBuilder('o')
            ->leftJoin(SuggestionModel::class, 'sug', 'WITH', 'sug.suggestion = o')
            ->leftJoin(Model::class, 'mod', 'WITH', 'o.model = mod')
            ->leftJoin(ModelStatus::class, 'sta', 'WITH', 'mod.status = sta')

            ->where('sug.categoryUp = :categorySearch')
            ->andWhere('sta.id = 1')
            ->orWhere('sta.id = 2')
            ->andWhere('sug.categoryUp = :categorySearch')
            //->andWhere('o.status != ' . Order::STATUS_AWAITING_PAYMENT . '') // exclude awaiting payments orders
            ->setParameter('categorySearch', $categorySearch);
        return $query_builder->getQuery()->getResult();
    }
}
