app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'

admin_logout:
    path: /{_locale}/%app.admin_directory%/logout
    requirements:
        _locale: '%app.locales%'

user_logout:
    path: /{_locale}/%app.user_directory%/logout
    requirements:
        _locale: '%app.locales%'

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"